export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <p>현대카드 3개월 무이자 이벤트중</p>
        {children}
      </body>
    </html>
  );
}
